=== UppariRahul/XML/CarCrashIncidents.xsd
<!-- 
MODULE : B9DA102 Data Storage Solutions for Data Analytics
GROUP B (Slot 4)

Subramaniam Kazhuparambil (10524303)
Rahul Ramchandra Uppari (10523807)
Deeksha Sharma (10522688) 
Mohit Singh (10525046)

SCHEMA
-->

<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:element name="CarCrashIncidents">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Driver_Dim" minOccurs="1" maxOccurs="unbounded"/>
<xsd:element ref="Vehicle_Dim" minOccurs="1" maxOccurs="unbounded"/>
<xsd:element ref="CaseDetail_Dim" minOccurs="1" maxOccurs="unbounded"/>
<xsd:element ref="CarCrashDate_Dim" minOccurs="1" maxOccurs="unbounded"/>
<xsd:element ref="CarCrashConditions_Dim" minOccurs="1" maxOccurs="unbounded"/>
<xsd:element ref="CrashIncident_Fact" minOccurs="1" maxOccurs="unbounded"/>
</xsd:sequence>
</xsd:complexType>
<xsd:key name="Person_PK">
<xsd:selector xpath="Driver_Dim/PersonKey"/>
<xsd:field xpath="."/>
</xsd:key>
<xsd:keyref name="Person_ref_Key" refer="Person_PK">
<xsd:selector xpath="CrashIncident_Fact/PersonKey"/>
<xsd:field xpath="."/>
</xsd:keyref>
<xsd:key name="Vehicle_PK">
<xsd:selector xpath="Vehicle_Dim/VehicleKey"/>
<xsd:field xpath="."/>
</xsd:key>
<xsd:keyref name="Vehicle_ref_Key" refer="Vehicle_PK">
<xsd:selector xpath="CrashIncident_Fact/VehicleKey"/>
<xsd:field xpath="."/>
</xsd:keyref>
<xsd:key name="Case_PK">
<xsd:selector xpath="CaseDetail_Dim/CaseKey"/>
<xsd:field xpath="."/>
</xsd:key>
<xsd:keyref name="Case_ref_Key" refer="Case_PK">
<xsd:selector xpath="CrashIncident_Fact/CaseKey"/>
<xsd:field xpath="."/>
</xsd:keyref>
<xsd:key name="Date_PK">
<xsd:selector xpath="CarCrashDate_Dim/CarCrashDateKey"/>
<xsd:field xpath="."/>
</xsd:key>
<xsd:keyref name="Date_ref_Key" refer="Date_PK">
<xsd:selector xpath="CrashIncident_Fact/CarCrashDateKey"/>
<xsd:field xpath="."/>
</xsd:keyref>
<xsd:key name="CrashConditions_PK">
<xsd:selector xpath="CarCrashConditions_Dim/CrashConditionsKey"/>
<xsd:field xpath="."/>
</xsd:key>
<xsd:keyref name="CrashCondition_ref_Key" refer="CrashConditions_PK">
<xsd:selector xpath="CrashIncident_Fact/CrashConditionsKey"/>
<xsd:field xpath="."/>
</xsd:keyref>
</xsd:element>
<xsd:element name="Driver_Dim">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="PersonKey" />
<xsd:element ref="PersonId" />
<xsd:element ref="InjurySeverity" />
<xsd:element ref="DriverDistractedBy" />
<xsd:element ref="NonMotoristSubstanceAbuse" />
<xsd:element ref="DriverLicenseState" />
<xsd:element ref="DriverSubstanceAbuse" />
<xsd:element ref="DriverAtFault" />
</xsd:sequence>
</xsd:complexType>
</xsd:element>
<xsd:element name="Vehicle_Dim">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="VehicleKey" />
<xsd:element ref="VehicleId" />
<xsd:element ref="VehicleBodyType" />
<xsd:element ref="VehicleDamageExtent" />
<xsd:element ref="VehicleMovement" />
<xsd:element ref="SpeedLimit" />
<xsd:element ref="DriverLessVehicle" />
<xsd:element ref="ParkedVehicle" />
<xsd:element ref="VehicleYear" />
<xsd:element ref="EquipmentProblems" />
</xsd:sequence>
</xsd:complexType>
</xsd:element>
<xsd:element name="CaseDetail_Dim">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="CaseKey" />
<xsd:element ref="ReportNumber" />
<xsd:element ref="AgencyName" />
<xsd:element ref="ACRSReportType" />
</xsd:sequence>
</xsd:complexType>
</xsd:element>
<xsd:element name="CarCrashDate_Dim">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="CarCrashDateKey" />
<xsd:element ref="FullDate" />
<xsd:element ref="DayOfWeek" />
<xsd:element ref="TypeOfDay" />
<xsd:element ref="DayOfMonth" />
<xsd:element ref="Month" />
<xsd:element ref="Quarter" />
<xsd:element ref="Year" />
</xsd:sequence>
</xsd:complexType>
</xsd:element>
<xsd:element name="CarCrashConditions_Dim">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="CrashConditionsKey" />
<xsd:element ref="LocalCaseNumber" />
<xsd:element ref="Weather" />
<xsd:element ref="SurfaceCondition" />
<xsd:element ref="Light" />
<xsd:element ref="TrafficControl" />
<xsd:element ref="CollisionType" />
<xsd:element ref="CollisionStreetName" />
<xsd:element ref="CollisionStreetType"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
<xsd:element name="CrashIncident_Fact">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="PersonKey"/>
<xsd:element ref="VehicleKey"/>
<xsd:element ref="CaseKey"/>
<xsd:element ref="CarCrashDateKey"/>
<xsd:element ref="CrashConditionsKey"/>
<xsd:element ref="CrashTime"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
<xsd:element name="PersonKey" type="xsd:int" />
<xsd:element name="PersonId" type="xsd:string" />
<xsd:element name="InjurySeverity" type="xsd:string"/>
<xsd:element name="DriverDistractedBy" type="xsd:string"/>
<xsd:element name="NonMotoristSubstanceAbuse" type="xsd:string"/>
<xsd:element name="DriverLicenseState" type="xsd:string"/>
<xsd:element name="DriverSubstanceAbuse" type="xsd:string"/>
<xsd:element name="DriverAtFault" type="xsd:string"/>
<xsd:element name="VehicleKey" type="xsd:int"/>
<xsd:element name="VehicleId" type="xsd:string"/>
<xsd:element name="VehicleBodyType" type="xsd:string"/>
<xsd:element name="VehicleDamageExtent" type="xsd:string"/>
<xsd:element name="VehicleMovement" type="xsd:string"/>
<xsd:element name="SpeedLimit" type="xsd:int"/>
<xsd:element name="DriverLessVehicle" type="xsd:string"/>
<xsd:element name="ParkedVehicle" type="xsd:string"/>
<xsd:element name="VehicleYear" type="xsd:int"/>
<xsd:element name="EquipmentProblems" type="xsd:string"/>
<xsd:element name="CaseKey" type="xsd:int"/>
<xsd:element name="ReportNumber" type="xsd:string"/>
<xsd:element name="AgencyName" type="xsd:string"/>
<xsd:element name="ACRSReportType" type="xsd:string"/>
<xsd:element name="CarCrashDateKey" type="xsd:string"/>
<xsd:element name="FullDate" type="xsd:date"/>
<xsd:element name="DayOfWeek" type="xsd:string"/>
<xsd:element name="TypeOfDay" type="xsd:string"/>
<xsd:element name="DayOfMonth" type="xsd:int"/>
<xsd:element name="Month" type="xsd:int"/>
<xsd:element name="Quarter" type="xsd:string"/>
<xsd:element name="Year" type="xsd:int"/>
<xsd:element name="CrashConditionsKey" type="xsd:int"/>
<xsd:element name="LocalCaseNumber" type="xsd:int"/>
<xsd:element name="Weather" type="xsd:string"/>
<xsd:element name="SurfaceCondition" type="xsd:string"/>
<xsd:element name="Light" type="xsd:string"/>
<xsd:element name="TrafficControl" type="xsd:string"/>
<xsd:element name="CollisionType" type="xsd:string"/>
<xsd:element name="CollisionStreetName" type="xsd:string"/>
<xsd:element name="CollisionStreetType" type="xsd:string"/>
<xsd:element name="CrashTime" type="xsd:time"/>
</xsd:schema>

=== UppariRahul/XML/CrashIncidents.xml
<!-- 
MODULE : B9DA102 Data Storage Solutions for Data Analytics
GROUP B (Slot 4)

Subramaniam Kazhuparambil (10524303)
Rahul Ramchandra Uppari (10523807)
Deeksha Sharma (10522688) 
Mohit Singh (10525046)

XML DOCUMENT
-->

<?xml version="1.0" encoding="utf-8"?>
<CarCrashIncidents xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="CarCrashIncidents.xsd">
<Driver_Dim>
<PersonKey>1</PersonKey>
<PersonId>E9396DD4-6507-4C0F-A160-C6C8845DEF7F</PersonId>
<InjurySeverity>NO_APPARENT_INJURY</InjurySeverity>
<DriverDistractedBy>NotDistracted</DriverDistractedBy>
<NonMotoristSubstanceAbuse>NA</NonMotoristSubstanceAbuse>
<DriverLicenseState>XX</DriverLicenseState>
<DriverSubstanceAbuse>Alcohol_Present</DriverSubstanceAbuse>
<DriverAtFault>Yes</DriverAtFault>
</Driver_Dim>
<Driver_Dim>
<PersonKey>2</PersonKey>
<PersonId>96F780B9-0BA8-4E0C-ACCB-CD4EFC90D62F</PersonId>
<InjurySeverity>NO_APPARENT_INJURY</InjurySeverity>
<DriverDistractedBy>NotDistracted</DriverDistractedBy>
<NonMotoristSubstanceAbuse>NA</NonMotoristSubstanceAbuse>
<DriverLicenseState>MD</DriverLicenseState>
<DriverSubstanceAbuse>NoneDetected</DriverSubstanceAbuse>
<DriverAtFault>Yes</DriverAtFault>
</Driver_Dim>
<Driver_Dim>
<PersonKey>3</PersonKey>
<PersonId>760EBB39-4307-46C1-8A1D-E09E6C15F202</PersonId>
<InjurySeverity>NO_APPARENT_INJURY</InjurySeverity>
<DriverDistractedBy>LOOKED_BUT_DID_NOT_SEE</DriverDistractedBy>
<NonMotoristSubstanceAbuse>NA</NonMotoristSubstanceAbuse>
<DriverLicenseState>MD</DriverLicenseState>
<DriverSubstanceAbuse>Non_Detected</DriverSubstanceAbuse>
<DriverAtFault>Yes</DriverAtFault>
</Driver_Dim>
<Driver_Dim>
<PersonKey>4</PersonKey>
<PersonId>2AFF3A21-F630-4478-AFB8-59EF68506073</PersonId>
<InjurySeverity>NO_APPARENT_INJURY</InjurySeverity>
<DriverDistractedBy>NotDistracted</DriverDistractedBy>
<NonMotoristSubstanceAbuse>N/A</NonMotoristSubstanceAbuse>
<DriverLicenseState>IL</DriverLicenseState>
<DriverSubstanceAbuse>AlcoholPresent</DriverSubstanceAbuse>
<DriverAtFault>Yes</DriverAtFault>
</Driver_Dim>
<Driver_Dim>
<PersonKey>5</PersonKey>
<PersonId>DA4F42B4-5AE0-4385-B77D-2E34A996200D</PersonId>
<InjurySeverity>NO_APPARENT_INJURY</InjurySeverity>
<DriverDistractedBy>NotDistracted</DriverDistractedBy>
<NonMotoristSubstanceAbuse>NoneDetected</NonMotoristSubstanceAbuse>
<DriverLicenseState>MD</DriverLicenseState>
<DriverSubstanceAbuse>NoneDetected</DriverSubstanceAbuse>
<DriverAtFault>No</DriverAtFault>
</Driver_Dim>
<Vehicle_Dim>
<VehicleKey>1</VehicleKey>
<VehicleId>AF0DBBDA-0CA4-4391-A1A7-32A0CC0B7056</VehicleId>
<VehicleBodyType>PassengerCar</VehicleBodyType>
<VehicleDamageExtent>Superficial</VehicleDamageExtent>
<VehicleMovement>MovigConstantSpeed</VehicleMovement>
<SpeedLimit>50</SpeedLimit>
<DriverLessVehicle>No</DriverLessVehicle>
<ParkedVehicle>No</ParkedVehicle>
<VehicleYear>2012</VehicleYear>
<EquipmentProblems>NA</EquipmentProblems>
</Vehicle_Dim>
<Vehicle_Dim>
<VehicleKey>2</VehicleKey>
<VehicleId>F835C9EA-2A0F-4C92-B125-EBC6AA3D603B</VehicleId>
<VehicleBodyType>SchoolBus</VehicleBodyType>
<VehicleDamageExtent>NO_DAMAGE</VehicleDamageExtent>
<VehicleMovement>Backing</VehicleMovement>
<SpeedLimit>5</SpeedLimit>
<DriverLessVehicle>No</DriverLessVehicle>
<ParkedVehicle>No</ParkedVehicle>
<VehicleYear>2007</VehicleYear>
<EquipmentProblems>NA</EquipmentProblems>
</Vehicle_Dim>
<Vehicle_Dim>
<VehicleKey>3</VehicleKey>
<VehicleId>B4579CDA-F41A-4764-9402-266AABC66AA9</VehicleId>
<VehicleBodyType>POLICE_VEHICLE_NON_EMERGENCY</VehicleBodyType>
<VehicleDamageExtent>Functional</VehicleDamageExtent>
<VehicleMovement>N/A</VehicleMovement>
<SpeedLimit>5</SpeedLimit>
<DriverLessVehicle>No</DriverLessVehicle>
<ParkedVehicle>No</ParkedVehicle>
<VehicleYear>2013</VehicleYear>
<EquipmentProblems>NA</EquipmentProblems>
</Vehicle_Dim>
<Vehicle_Dim>
<VehicleKey>4</VehicleKey>
<VehicleId>B887AAF8-124E-42FB-9DD6-57CCC1831E46</VehicleId>
<VehicleBodyType>Other</VehicleBodyType>
<VehicleDamageExtent>Disabling</VehicleDamageExtent>
<VehicleMovement>Changing_Lanes</VehicleMovement>
<SpeedLimit>40</SpeedLimit>
<DriverLessVehicle>No</DriverLessVehicle>
<ParkedVehicle>No</ParkedVehicle>
<VehicleYear>2008</VehicleYear>
<EquipmentProblems>NA</EquipmentProblems>
</Vehicle_Dim>
<Vehicle_Dim>
<VehicleKey>5</VehicleKey>
<VehicleId>0BC12A34-4F84-4886-A820-49214BE06384</VehicleId>
<VehicleBodyType>Van</VehicleBodyType>
<VehicleDamageExtent>Disabling</VehicleDamageExtent>
<VehicleMovement>Slowing_Or_Stoping</VehicleMovement>
<SpeedLimit>35</SpeedLimit>
<DriverLessVehicle>No</DriverLessVehicle>
<ParkedVehicle>No</ParkedVehicle>
<VehicleYear>2007</VehicleYear>
<EquipmentProblems>NA</EquipmentProblems>
</Vehicle_Dim>
<CaseDetail_Dim>
<CaseKey>1</CaseKey>
<ReportNumber>MCP28910063</ReportNumber>
<AgencyName>MontgomeryCountyPolice</AgencyName>
<ACRSReportType>PropertyDamageCrash</ACRSReportType>
</CaseDetail_Dim>
<CaseDetail_Dim>
<CaseKey>2</CaseKey>
<ReportNumber>EJ7852000Q</ReportNumber>
<AgencyName>Gaithersburg_Police_Depar</AgencyName>
<ACRSReportType>InjuryCrash</ACRSReportType>
</CaseDetail_Dim>
<CaseDetail_Dim>
<CaseKey>3</CaseKey>
<ReportNumber>DM84390011</ReportNumber>
<AgencyName>Takoma_Park_Police_Depart</AgencyName>
<ACRSReportType>Property_Damage_Crash</ACRSReportType>
</CaseDetail_Dim>
<CaseDetail_Dim>
<CaseKey>4</CaseKey>
<ReportNumber>MCP1251000S</ReportNumber>
<AgencyName>MontgomeryCountyPolice</AgencyName>
<ACRSReportType>InjuryCrash</ACRSReportType>
</CaseDetail_Dim>
<CaseDetail_Dim>
<CaseKey>5</CaseKey>
<ReportNumber>DD5583003C</ReportNumber>
<AgencyName>RockvillePoliceDepartme</AgencyName>
<ACRSReportType>PropertyDamageCrash</ACRSReportType>
</CaseDetail_Dim>
<CarCrashDate_Dim>
<CarCrashDateKey>1</CarCrashDateKey>
<FullDate>2015-01-01</FullDate>
<DayOfWeek>Weekday</DayOfWeek>
<TypeOfDay>Wednesday</TypeOfDay>
<DayOfMonth>1</DayOfMonth>
<Month>1</Month>
<Quarter>Q1</Quarter>
<Year>2015</Year>
</CarCrashDate_Dim>
<CarCrashDate_Dim>
<CarCrashDateKey>2</CarCrashDateKey>
<FullDate>2016-01-16</FullDate>
<DayOfWeek>Weekday</DayOfWeek>
<TypeOfDay>Friday</TypeOfDay>
<DayOfMonth>16</DayOfMonth>
<Month>1</Month>
<Quarter>Q1</Quarter>
<Year>2016</Year>
</CarCrashDate_Dim>
<CarCrashDate_Dim>
<CarCrashDateKey>3</CarCrashDateKey>
<FullDate>2017-04-23</FullDate>
<DayOfWeek>Weekend</DayOfWeek>
<TypeOfDay>Saturday</TypeOfDay>
<DayOfMonth>23</DayOfMonth>
<Month>4</Month>
<Quarter>Q2</Quarter>
<Year>2017</Year>
</CarCrashDate_Dim>
<CarCrashDate_Dim>
<CarCrashDateKey>4</CarCrashDateKey>
<FullDate>2018-07-30</FullDate>
<DayOfWeek>Weekend</DayOfWeek>
<TypeOfDay>Sunday</TypeOfDay>
<DayOfMonth>30</DayOfMonth>
<Month>7</Month>
<Quarter>Q3</Quarter>
<Year>2018</Year>
</CarCrashDate_Dim>
<CarCrashDate_Dim>
<CarCrashDateKey>5</CarCrashDateKey>
<FullDate>2019-06-18</FullDate>
<DayOfWeek>Weekday</DayOfWeek>
<TypeOfDay>Monday</TypeOfDay>
<DayOfMonth>18</DayOfMonth>
<Month>6</Month>
<Quarter>Q2</Quarter>
<Year>2019</Year>
</CarCrashDate_Dim>
<CarCrashConditions_Dim>
<CrashConditionsKey>1</CrashConditionsKey>
<LocalCaseNumber>1800</LocalCaseNumber>
<Weather>Clear</Weather>
<SurfaceCondition>Dry</SurfaceCondition>
<Light>DayLight</Light>
<TrafficControl>NA</TrafficControl>
<CollisionType>SameDirRearEnd</CollisionType>
<CollisionStreetName>Gros</CollisionStreetName>
<CollisionStreetType>County</CollisionStreetType>
</CarCrashConditions_Dim>
<CarCrashConditions_Dim>
<CrashConditionsKey>2</CrashConditionsKey>
<LocalCaseNumber>16000924</LocalCaseNumber>
<Weather>Clear</Weather>
<SurfaceCondition>Dry</SurfaceCondition>
<Light>DARK_NO_LIGHTS</Light>
<TrafficControl>No_Controls</TrafficControl>
<CollisionType>SameDirRearEnd</CollisionType>
<CollisionStreetName>BLACKBURN_RD</CollisionStreetName>
<CollisionStreetType>County</CollisionStreetType>
</CarCrashConditions_Dim>
<CarCrashConditions_Dim>
<CrashConditionsKey>3</CrashConditionsKey>
<LocalCaseNumber>180052478</LocalCaseNumber>
<Weather>Raining</Weather>
<SurfaceCondition>Wet</SurfaceCondition>
<Light>DARK_NO_LIGHTS</Light>
<TrafficControl>No_Controls</TrafficControl>
<CollisionType>SingleVehicle</CollisionType>
<CollisionStreetName>N/A</CollisionStreetName>
<CollisionStreetType>N/A</CollisionStreetType>
</CarCrashConditions_Dim>
<CarCrashConditions_Dim>
<CrashConditionsKey>4</CrashConditionsKey>
<LocalCaseNumber>180052520</LocalCaseNumber>
<Weather>Cloudy</Weather>
<SurfaceCondition>Dry</SurfaceCondition>
<Light>DayLight</Light>
<TrafficControl>No_Controls</TrafficControl>
<CollisionType>SameDirRearEnd</CollisionType>
<CollisionStreetName>ODENDHAL_AVE</CollisionStreetName>
<CollisionStreetType>Municipality</CollisionStreetType>
</CarCrashConditions_Dim>
<CarCrashConditions_Dim>
<CrashConditionsKey>5</CrashConditionsKey>
<LocalCaseNumber>180052520</LocalCaseNumber>
<Weather>Cloudy</Weather>
<SurfaceCondition>Dry</SurfaceCondition>
<Light>DayLight</Light>
<TrafficControl>No_Controls</TrafficControl>
<CollisionType>SameDirRearEnd</CollisionType>
<CollisionStreetName>ODENDHAL_AVE</CollisionStreetName>
<CollisionStreetType>Municipality</CollisionStreetType>
</CarCrashConditions_Dim>
<CrashIncident_Fact>
<PersonKey>1</PersonKey>
<VehicleKey>1</VehicleKey>
<CaseKey>1</CaseKey>
<CarCrashDateKey>1</CarCrashDateKey>
<CrashConditionsKey>1</CrashConditionsKey>
<CrashTime>00:30:00</CrashTime>
</CrashIncident_Fact>
<CrashIncident_Fact>
<PersonKey>2</PersonKey>
<VehicleKey>2</VehicleKey>
<CaseKey>2</CaseKey>
<CarCrashDateKey>2</CarCrashDateKey>
<CrashConditionsKey>2</CrashConditionsKey>
<CrashTime>10:17:17</CrashTime>
</CrashIncident_Fact>
<CrashIncident_Fact>
<PersonKey>3</PersonKey>
<VehicleKey>3</VehicleKey>
<CaseKey>3</CaseKey>
<CarCrashDateKey>3</CarCrashDateKey>
<CrashConditionsKey>3</CrashConditionsKey>
<CrashTime>08:57:00</CrashTime>
</CrashIncident_Fact>
<CrashIncident_Fact>
<PersonKey>4</PersonKey>
<VehicleKey>4</VehicleKey>
<CaseKey>4</CaseKey>
<CarCrashDateKey>4</CarCrashDateKey>
<CrashConditionsKey>4</CrashConditionsKey>
<CrashTime>05:37:12</CrashTime>
</CrashIncident_Fact>
<CrashIncident_Fact>
